<?xml version="1.0"?>

<robot
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    <include filename="$(find eklavya_description)/urdf/params.xacro"/>

	<property name="wheel_mass" value="2.6" /> <!-- in kg-->

  <macro name="eklavya_wheel" params="suffix parent *origin">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <insert_block name="origin" />
      <axis xyz="0 1 0" />
      <anchor xyz="0 0 0" />
      <limit effort="100" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />
      <parent link="${parent}" />
      <child link="${parent}_${suffix}_wheel_link" />
    </joint>

    <link name="${parent}_${suffix}_wheel_link">
      <cylinder_inertial_with_origin_wheel radius="${wheel_x_size/2}" length="${wheel_z_size}" mass="${wheel_mass}" origin="0 0 0" />
	  <visual>
        <eklavya_wheel_mesh suffix="${suffix}" />  
		<material name="Red" />
      </visual>

      <collision>
		  <origin xyz="0 0 0" rpy="1.570796327 0 0" />
		  <geometry>
			 <cylinder radius="${wheel_x_size/2}" length="0.09"/>
	      </geometry>
      </collision>
    </link>

    <eklavya_wheel_surface suffix="${suffix}" parent="${parent}" />
    
    <!-- Transmission is important to link the joints and the controller -->
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="${parent}_${suffix}_wheel_trans">
      <actuator name="${parent}_${suffix}_wheel_motor" />
      <joint name="${parent}_${suffix}_wheel_joint" />
      <mechanicalReduction>1.0</mechanicalReduction>
       <!-- <motorTorqueConstant>1</motorTorqueConstant>-->
    </transmission>
  </macro>
</robot>

